version: ~> 1.0
dist: bionic
language: python
cache:
  pip: true
  directories:
    - node_modules
jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: nightly
    - language: node_js
      install:
        - npm install --no-optional --no-audit --progress=false
      script:
        - npm run lint
install:
  - pip install pipenv pycodestyle
  - pipenv install --dev
script:
  - pipenv run python -m curlylint.test
  - pipenv run pycodestyle curlylint/
branches:
  except:
    - gh-pages
notifications:
  email: false
