version: ~> 1.0
dist: bionic
language: python
cache:
  pip: true
  directories:
    - node_modules
jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: nightly
    - language: node_js
      install:
        - npm install --no-optional --no-audit --progress=false
      script:
        - npm run lint
install:
  - pip install -e '.[dev]'
script:
  - make lint
  - make test
branches:
  except:
    - gh-pages
notifications:
  email: false
