version: ~> 1.0
dist: bionic
language: python
cache:
  pip: true
  directories:
    - node_modules
jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      script:
        - make lint
        - make test-coverage
    - language: node_js
      install:
        - npm install --no-optional --no-audit --progress=false
        - npm --prefix website install
      script:
        - npm run lint
        - npm --prefix website run build
install:
  - pip install -e '.[dev]'
script:
  - make test-coverage
branches:
  except:
    - gh-pages
notifications:
  email: false
